apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - host: {{ .Values.name }}.com
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.name }}
            port:
              number: 80
        path: /
        pathType: Prefix