apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
namespace: dev
images:
- name: myapi
  newName: acrdevuks001.azurecr.io/myapi
  newTag: 1.0.5
configMapGenerator:
  - name: myapi
    literals:
      - env_var=test variable
      - kv_name=<key vault instance name>
resources:
- ../base
patchesStrategicMerge:
- set-client-id-service-account.yaml